#!/bin/bash
# return_bash_match.sh
# This script is used on the
# back-end to do the "Match"
#
# Take the escaped REGEX string generated by the site and use it in the 'regex' param

var="$1"

drare='^v?(.)?([0-9]+).([0-9]+).([0-9]+)(-(pre|rc|dev|alpha)([0-9]+))?(-git[0-9a-z]{6,8})$'
prere='^v?(.)?([0-9]+).([0-9]+).([0-9]+)(-(pre|rc)([0-9]+))$'
devre='^v?(.)?([0-9]+).([0-9]+).([0-9]+)(-(dev|alpha)([0-9]+))$'
relre='^v?(.)?([0-9]+).([0-9]+).([0-9]+)$'

if [[ "$var" =~ $drare ]]
then
    echo "${var} matches draft release regex"
fi

if [[ "$var" =~ $prere ]]
then
    echo "${var} matches prerelease regex"
fi

if [[ "$var" =~ $devre ]]
then
    echo "${var} matches devrelease regex"
fi

if [[ "$var" =~ $relre ]]
then
    echo "${var} matches release regex"
fi
